### get_document
GET http://localhost:8000/api/v1/document/:id
accept: application/json


### patch_document
PATCH http://localhost:8000/api/v1/document/:id
content-type: application/json

{
  "title": "Document Title",
  "content": {}
}


### login
POST http://localhost:8000/api/v1/login
content-type: application/json
accept: application/json

{
  "login": "admin",
  "password": "admin"
}


### current_user
GET http://localhost:8000/api/v1/login
accept: application/json


### logout
DELETE http://localhost:8000/api/v1/login


### update_current_user
PATCH http://localhost:8000/api/v1/login
content-type: application/json

{
  "username": "bob",
  "name": "Bob Bobbington",
  "email": "bob@example.com",
  "password": "i am bob"
}
