[package]
name = "sapiprudentia"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
rocket_dyn_templates = { version = "0.1.0-rc.3", features = ["tera"] }
shuttle-aws-rds = { version = "0.29.0", features = ["postgres"] }
shuttle-rocket = "0.29.0"
shuttle-runtime = "0.29.0"
sqlx = { version = "0.7.2", features = ["postgres", "macros"] }
tokio = "1.26.0"
