services:
  backend:
    image: ghcr.io/thesupergamer20578/sapiprudentia-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: ${SECRET_KEY:?Generate with openssl rand -base64 32}
      CORS_ALLOWED_ORIGINS: ${FRONTEND_URL:-http://localhost:3000}
      DATABASE_URL: postgres://${DATABASE_USERNAME:-sapiprudentia}:${DATABASE_PASSWORD:-sapiprudentia}@db/sapiprudentia
    depends_on:
      - db

  frontend:
    image: ghcr.io/thesupergamer20578/sapiprudentia-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PUBLIC_API_URL: ${BACKEND_URL:-http://localhost:8000}
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-sapiprudentia}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-sapiprudentia}
