query Subject($id: Int!) {
    subject(id: $id) {
        id
        name
        class
        active
    }
    todos {
        id
        title
        subject {
            id
            name
        }
        archived
        completed
        due
        parent {
            id
        }
    }
}